name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'  # This can be changed to deploy a subdirectory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
